### ISSUE TITLE
[FR] Annotate each completed task with a timestamp

### ISSUE THREAD

**Issue by HarshIceHummer** [Gnopps/obsidian-rewarder#2]
The "Save task in daily note" feature of Rewarder can have this option. It'd be very useful to know at { what time } of { which date } the task was completed. Something like : 

[x] Task completed ( at 10-22-2022 06:10:12 PM)

**Comment by Gnopps** [comment]
Thanks for this idea! I implemented in the latest version now (https://github.com/Gnopps/obsidian-rewarder/releases/tag/0.3.1).
