### ISSUE TITLE
Not working when completing task through Keyboard shortcut

### ISSUE THREAD

**Issue by William-A-A** [Gnopps/obsidian-rewarder#4]
use standard " CTRL +L" to toggle checkbox and finish task >> does not gimme my cup of tea :'( . 
Outside of that the plugin is Genius  :p

**Comment by Gnopps** [comment]
Thanks for the feedback! I think this would be great but I unfortunately haven't figured out a way to track "task completed" in Obsidian as opposed to "task clicked".

**Comment by Gnopps** [comment]
This was fixed in the latest release (https://github.com/Gnopps/obsidian-rewarder/releases/tag/0.4.0) thanks to @jiyee

**Comment by kevinvonjames** [comment]
doesn't seem to be working for me
