### ISSUE TITLE
does not work under Obsidian Version 1.3.5 (Installer 1.3.4)

### ISSUE THREAD

**Issue by paregorios** [Gnopps/obsidian-rewarder#6]
Using Obsidian Version 1.3.5 (Installer 1.3.4) and Tasks plugin 3.10.0 under macOS Monterey 12.6.6 (M1 chip). Clean install of Rewarder plugin. Used command to generate `Rewards.md`. No rewards ever show. Even after dialing up percentage reward to 100% and restarting Obsidian, no rewards are generated.

**Comment by Gnopps** [comment]
This is now fixed in the latest release. (https://github.com/Gnopps/obsidian-rewarder/releases/tag/0.3.1)

**Comment by paregorios** [comment]
Thank you!
