### ISSUE TITLE
[FR] Choose a Daily Note Heading to write rewards/completed tasks to

### ISSUE THREAD

**Issue by technotherion** [Gnopps/obsidian-rewarder#7]
I have quite a few plugins and integrations fighting to write to the last line of my daily notes. 
Could there be a setting for where in the daily notes the rewards and tasks save to? 
E.g. "## Reward" or "## CompletedTasks", and create them if they do not yet exist? 

Loving this plugin so far. Back to procrastinating...

**Comment by Gnopps** [comment]
Thanks for your idea! I do see the usefulness but won't have time to work on this in the near future.

**Comment by Gnopps** [comment]
This was added in the latest release (https://github.com/Gnopps/obsidian-rewarder/releases/tag/0.4.0) thanks to @jiyee
